<section class="col-xl-11 col-lg-11 col-md-12 col-sm-12 m-auto d-flex flex-wrap justify-content-between p-5">
		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 d-flex  mt-4 mb-4 flex-wrap">
			<div class="w-100 p-4">
			  <div class="w-100">
			  	 <h5 class="w-100 text-green-s1 text-lg font-weight-bold p-3" >Antecedentes</h5>
			  	 <p class="text-dark font-weight-light text-md p-3">Con motivo de la creación del Sistema Nacional Anticorrupción, el 18 de julio de 2016, se publicó en el Diario Oficial de la Federación, la Ley General del Sistema Nacional Anticorrupción, en cuyo artículo 36 se establece que las leyes de las entidades federativas desarrollarán la integración, atribuciones, y funcionamiento de los Sistemas Locales. Lo anterior, motivó la reforma de la Constitución Política del Estado de Yucatán, en cuyo artículo 101 bis, se establece la creación del Sistema Estatal Anticorrupción de Yucatán, como la instancia de coordinación entre las autoridades del orden estatal y municipal competentes en la prevención, detección y sanción de responsabilidades administrativas y hechos de corrupción, así como en la fiscalización y control de recursos públicos.</p>
				 <p class="text-dark font-weight-light text-md p-3">Derivado de lo anterior, en fecha 18 de julio de 2017, se publicó en el Diario Oficial del Gobierno del Estado de Yucatán, la Ley del Sistema Estatal Anticorrupción de Yucatán, siendo que el artículo 10 del citado ordenamiento, prevé que el Comité Coordinador del Sistema Estatal Anticorrupción sea instancia superior de coordinación del sistema, siendo uno de sus objetos establecer procedimientos para la coordinación entre los entes públicos en la prevención, detección y sanción de faltas administrativas y hechos de corrupción, así como en la fiscalización y control de recursos públicos.</p>
				<p class="text-dark font-weight-light text-md p-3">Por otra parte, los artículos 22 y 23, fracción VII, de la mencionada Ley, establecen que el Comité de Participación Ciudadana es la instancia que tiene como objetivo coadyuvar al cumplimiento del objeto del comité coordinador, y que una de sus atribuciones es proponerle mecanismos para que la sociedad participe en la prevención y denuncia de faltas administrativas y hechos de corrupción. Lo anterior, refleja el espíritu del Sistema Estatal Anticorrupción de otorgar a los ciudadanos una participación directa, dinámica y activa en el combate a la corrupción, lo cual requiere la implementación de un mecanismo que permita exponer los hechos que se pretenden combatir, a través de la generación de políticas públicas integrales.
				<p class="text-dark font-weight-light text-md p-3">Por su parte, los artículos 30 y 31 de la mencionada Ley, establecen que la Secretaría Ejecutiva del Sistema Estatal Anticorrupción es un organismo público descentralizado, con personalidad jurídica y patrimonio propio, con autonomía técnica y de gestión, y que tiene por objeto fungir como órgano de apoyo técnico del Comité Coordinador, a efecto de proveerle la asistencia técnica así como los insumos necesarios para el desempeño de sus atribuciones, conforme a lo dispuesto en la fracción III del artículo 101 Bis de la Constitución Política del Estado de Yucatán.</p>
			  </div>
			</div>
		</div>
</section>